### ISSUE TITLE
Downloader: API Result error. 

### ISSUE THREAD

**Issue by may1112** [Justson/Downloader#13]
请问我批量下载的时候，会报这个提示，但是并不影响下载。
Downloader: API Result error. 

下载的时候app异常崩溃，下载中的视频全部归为0，无法继续下载，请问有什么解决办法吗？

**Comment by Justson** [comment]
API Result error， 这个异常是Downloader抛出的吗？

**Comment by may1112** [comment]
我不确定，因为打印出来 就是包名 + Downloader: API Result error.
我搜索了我的项目并没有这巨打印，所以来这里询问一下你。

**Comment by Justson** [comment]
贴下异常信息吗

**Comment by may1112** [comment]
![image](https://user-images.githubusercontent.com/20389396/89162884-4e694d00-d5a7-11ea-874d-5d6fffddcb2e.png)
![image](https://user-images.githubusercontent.com/20389396/89162908-56c18800-d5a7-11ea-87b1-b0a5fcf0ed35.png)
请问这个可以吗

**Comment by may1112** [comment]
exception.getMessage()：API Result error. DOWNLOAD_RESULT_FAIL 
 exception.getDetailMessage()：initVideoCopies result is fail

**Comment by Justson** [comment]
print 一下堆栈信息

**Comment by may1112** [comment]
![image](https://user-images.githubusercontent.com/20389396/89242855-17da1380-d635-11ea-8484-0a6b7f6097b9.png)
zhegema?
