### ISSUE TITLE
断点续传稳定性问题

### ISSUE THREAD

**Issue by ryanxia2016** [Justson/Downloader#15]
下载一个50MB的文件，中间故意杀进程，以观察断点续传的效果。

试了七八次，有2次最终下载的文件MD5校验失败。

应该是杀进程时文件写入，与下次恢复传输时的校验机制还需要完善

我看xutils里，每次断点续传开始时，会把断点前移512字节，校验本地文件最后的512个字节，是否与服务器上的相同，如果相同则续传，否则放弃重新开始。

**Comment by Justson** [comment]
欢迎PR， 能把你的下载地址给我看下吗？

**Comment by ryanxia2016** [comment]
可以看看这里的实现
https://github.com/wyouflf/xUtils3/blob/287c5aa9d378fecd9ecd609cfbb0ab544b860ccf/xutils/src/main/java/org/xutils/http/loader/FileLoader.java
