### ISSUE TITLE
ERROR: Failed to resolve: com.download.library:Downloader:4.1.5

### ISSUE THREAD

**Issue by abosaqer** [Justson/Downloader#22]
Hi i hope you are  fine :D

i always get this error "ERROR: Failed to resolve: com.download.library:Downloader:4.1.5"

i add maven { url "https://jitpack.io" }
and i add ::
implementation "com.download.library:Downloader:4.1.5"

but not working 

can you help me 

thanks

**Comment by Justson** [comment]
implementation 'com.github.Justson:Downloader:v4.1.9'
