### ISSUE TITLE
Google Play  Suspended

### ISSUE THREAD

**Issue by xiaoxiaohua333** [Justson/Downloader#23]
在使用了com.download.library:downloader-androidx:4.1.4 后 ，Google play 被遭到封停！

Your app contains content that doesn’t comply with the Device and Network Abuse policy. We found your app is using a non-compliant version of Loan Download SDK which contains code to download or install applications from unknown sources outside of Google Play.

**Comment by Justson** [comment]
从上面的信息看, 看不到是Downloader SDK 导致的

**Comment by xiaoxiaohua333** [comment]
这个Google play 对其他应用的回复

https://appyet.com/forum/index.php?threads/befor-4-0-18-update-4-apps-suspended-after-4-0-18-all-apps-suspended-loan-download-sdk.3317/

**Comment by xiaoxiaohua333** [comment]
REQUEST_INSTALL_PACKAGES

以及支持APK下载完成后自动安装 
https://github.com/Justson/Downloader/blob/master/library/src/main/java/com/download/library/Runtime.java

**Comment by Justson** [comment]
这个不太可能, 这个只是安装应用权限, 你可以尝试把这一块去掉,提交审核试下

**Comment by HaitianZhuu** [comment]
遇到同样的问题了，突然app被下架，从appyet论坛那边过来的。
这样使用的：
```
    // webview library
    implementation 'com.just.agentweb:agentweb:4.1.3'
    implementation 'com.just.agentweb:filechooser:4.1.3'
    implementation 'com.download.library:Downloader:4.1.3'
```
准备移除filechooser和downloader

**Comment by xiaoxiaohua333** [comment]
目前看 应该是 download 问题

https://github.com/Justson/Downloader/blob/master/library/src/main/java/com/download/library/Runtime.java

``` java
  public String getMIMEType(File f) {  
...

支持APK

 }

```
以及下载完成后可以安装

**Comment by Justson** [comment]
从上面信息看，Google Play 不允许下载未知来源的App， 可以把`REQUEST_INSTALL_PACKAGES `权限去掉试试

**Comment by Justson** [comment]
`REQUEST_INSTALL_PACKAGES ` 下个版本会把这个权限去掉， 有需要的用户需要自行加上

**Comment by xiaoxiaohua333** [comment]
建议可以在 agent-web 引用 ，或者使用这个sdk 说明文档里面备注下  存在Google play 限制

现在APP被GP封停了，GP要求修改包名....
先申诉看看

**Comment by Justson** [comment]
`implementation 'com.github.Justson:Downloader:v4.2.0' `  已发布
