### ISSUE TITLE
自动打开apk文件失败

### ISSUE THREAD

**Issue by yaojunqi** [Justson/Downloader#24]
下载apk自动打开失败，第一次成功，第二失败，第三次成功。。。
方法如下：
 DownloadImpl.with(App.getInstance())
                .url(url)
                //自定义路径需指定目录和authority(FileContentProvide),需要相对应匹配才能启动通知，和自动打开文件
                .target(file, BuildConfig.APPLICATION_ID + ".provider")
                .addHeader("Range", "bytes=0-")//添加请求头
                .autoOpenIgnoreMD5()//下载完成后自动打开文件，不做文件校验
                .setOpenBreakPointDownload(false)//打开断点续传
                .enqueue(new DownloadListenerAdapter()

**Comment by Justson** [comment]
可以设置md5 严格验证后打开
