### ISSUE TITLE
DownloadNotifier.java line:110 com.download.library.DownloadNotifier.initBuilder

### ISSUE THREAD

**Issue by Sach16** [Justson/Downloader#30]
Fatal Exception: java.lang.IllegalArgumentException com.monsterindia.seeker.views: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

Please update the DownloadNotifier line 110 PendingIntent with the flag FLAG_IMMUTABLE

**Comment by Sach16** [comment]
HI @Justson, 
We are using your library in our product Android application from a very long time. And as from version 31 PendingIntents are handled differently. We need you to furnish this and provide us an updated version of the library to download.
Thanks

**Comment by Sach16** [comment]
Hi @Justson 
Just to get an update from you that, can the library be fixed as soon as possible, Due to continuous usage of our product the library plays a very crucial part in it. Hence just asking to please fix the issue asap
com.download.library.DownloadNotifier in line 110 shown below, needs a fix

`mBuilder.setContentIntent(PendingIntent.getActivity(mContext, 200, new Intent(), PendingIntent.FLAG_UPDATE_CURRENT));`

Needs to be updated as 

`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) { 
mBuilder.setContentIntent(PendingIntent.getActivity(mContext, 200, new Intent(),  PendingIntent.FLAG_IMMUTABLE or  PendingIntent.FLAG_UPDATE_CURRENT));
} else {
mBuilder.setContentIntent(PendingIntent.getActivity(mContext, 200, new Intent(), PendingIntent.FLAG_UPDATE_CURRENT));
}`

**Comment by Justson** [comment]
implementation 'com.github.Justson:Downloader:v5.0.4-androidx'
