### ISSUE TITLE
5.0.3 还是有个PendingIntent的问题

### ISSUE THREAD

**Issue by NiceJC** [Justson/Downloader#33]
我是agentWeb导入的下载 androidX 5.0.3，测试下载还是会报 Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

**Comment by Justson** [comment]
implementation 'com.github.Justson:Downloader:v5.0.4-androidx'
