### ISSUE TITLE
异步下载 地址相同的问题

### ISSUE THREAD

**Issue by leeef** [Justson/Downloader#4]
大佬 我用异步下载一组文件， 在监听结果onResult里面判断下载完毕然后递归循环下一个文件，本来之前是好的，但是最近出现一个问题 ，因为后台配了一些测试数据，这组文件地址有些可能是一样的，这样导致这个文件只能下载一遍，在一次循环中就只能请求一下，第二次好像就请求不到，不能下载了，而且日志没有报错信息，想问下是什么情况

**Comment by Justson** [comment]
相同地址，第二次enqueue，会返回false， 无法下载。

**Comment by leeef** [comment]
大佬 这个可以自定义修改让他下载么

**Comment by Justson** [comment]
下载中，不可以重复下载的

**Comment by leeef** [comment]
那如果我下载完一个文件 可以把当前下载完的文件从当前队列移除么

**Comment by leeef** [comment]
可以了 之前应该是在onResult里面直接递归 这样下载的任务都在一个列表里，所有文件下载完才算是下载完成，现在改了下形式，用handler的形式单个文件下完成就会移除队列了。
