### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by rahul81281** [Justson/Downloader#42]
dear sir can you please help me i need this project so badly i am struck i have finished my project only download feature is needed i found your repo.. after so many trouble this is the only one which i want in my project my project is targeting android 13 and still i am having problems what am i doing wrong i dont understand .. i have sucsessfully iported your repo in my project and downloading also starts but files are not saving in dir need help i hope you will help me to finish my project need this repo so bad so please cooparete with me i will also buy you a coffee for my pleasure...

**Comment by rahul81281** [comment]
i have solved some issues but after download completed i want keep downloaded item in recyclerview after closing app it restarts download
need help

**Comment by Justson** [comment]
This library does not support this feature, which may require you to develop

**Comment by rahul81281** [comment]
Thank you for your response sir,
Can you help me to achieve. I am developing appmarket app I have almost
finished project all I need is download manager that works like other
appmarket like happymod or apkmody...or like acmarket any of this one if
you have time I am not pro I tried everything on Google and YouTube finally
found your lib which works almost similar to other app market...anyway
thank you so much again if you can help me it would be great for me.👍
