### ISSUE TITLE
用replugin加载后的插件，下载东西会报错

### ISSUE THREAD

**Issue by woleigeququ** [Justson/Downloader#5]
请教一下，用replugin加载后的插件，打开一个网页后下载东西会停到90%多，再点击一下网页就会崩溃，报错信息：

Process: com.qihoo360.replugin.sample.host, PID: 2723
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:605)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:579)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:417)
        at com.just.agentweb.AgentWebUtils.getUriFromFileForN(AgentWebUtils.java:228)
        at com.just.agentweb.AgentWebUtils.getUriFromFile(AgentWebUtils.java:220)
        at com.just.agentweb.AgentWebUtils.setIntentDataAndType(AgentWebUtils.java:239)
        at com.just.agentweb.AgentWebUtils.getCommonFileIntentCompat(AgentWebUtils.java:661)
        at com.just.agentweb.download.DefaultDownloadImpl.preDownload(DefaultDownloadImpl.java:212)
        at com.just.agentweb.download.DefaultDownloadImpl.onDownloadStartInternal(DefaultDownloadImpl.java:145)
        at com.just.agentweb.download.DefaultDownloadImpl.access$000(DefaultDownloadImpl.java:58)
        at com.just.agentweb.download.DefaultDownloadImpl$1.run(DefaultDownloadImpl.java:112)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by Justson** [comment]
贴一下代码

**Comment by woleigeququ** [comment]
代码就是主程序RePlugin.startActivity(this, intent);
插件启动后去加载一个有下载的url
private IAgentWebSettings getAbsAgentSettings() {
        return new AbsAgentWebSettings() {
            private AgentWeb mAgentWeb;

            @Override
            protected void bindAgentWebSupport(AgentWeb agentWeb) {
                this.mAgentWeb = agentWeb;
            }

            @Override
            public WebListenerManager setDownloader(WebView webView, android.webkit.DownloadListener downloadListener) {
                return super.setDownloader(webView,
                        DefaultDownloadImpl.create(
                                (Activity) webView.getContext(),
                                webView,
                                mSimpleDownloadListener,
                                this.mAgentWeb.getPermissionInterceptor()));
            }
        };
    }

    private DownloadListener mSimpleDownloadListener = new DownloadListener() {
        /**
         *
         * @param url                下载链接
         * @param userAgent          UserAgent
         * @param contentDisposition ContentDisposition
         * @param mimetype           资源的媒体类型
         * @param contentLength      文件长度
         * @param extra              下载配置 ， 用户可以通过 Extra 修改下载icon ， 关闭进度条 ， 是否强制下载。
         * @return true 表示用户处理了该下载事件 ， false 交给 AgentWeb 下载
         */
        @Override
        public boolean onStart(String url, String userAgent, String contentDisposition, String mimetype, long contentLength, Extra extra) {
            if(!mOperator.isAccessWorkPage) {
                return true;
            }

            extra.setBreakPointDownload(true) // 是否开启断点续传
                    .setConnectTimeOut(6000) // 连接最大时长
                    .setBlockMaxTime(10 * 60 * 1000)  // 以8KB位单位，默认60s ，如果60s内无法从网络流中读满8KB数据，则抛出异常
                    .setDownloadTimeOut(Long.MAX_VALUE) // 下载最大时长
                    .setParallelDownload(true)  // 串行下载更节省资源
                    .setEnableIndicator(true)  // false 关闭进度通知
//                    .addHeader("Cookie", "xx") // 自定义请求头
                    .setAutoOpen(true) // 下载完成自动打开
                    .setForceDownload(true); // 强制下载，不管网络类型
            if(downLoadListener!=null){
                downLoadListener.downStart();
            }
            return false;
        }

        /**
         * @param url  下载链接
         * @param loaded  已经下载的长度
         * @param length    文件的总大小
         * @param usedTime   耗时 ，单位ms
         * 注意该方法回调在子线程 ，线程名 AsyncTask #XX 或者 AgentWeb # XX
         */
        @Override
        public void onProgress(String url, long loaded, long length, long usedTime) {
//            int progress = (int) ((loaded) / (float) length * 100);
//            Log.e("temp","下载进度 :"+ progress );
            super.onProgress(url, loaded, length, usedTime);
        }

        /**
         * @param path 文件的绝对路径
         * @param url  下载地址
         * @param throwable    如果异常，返回给用户异常
         * @return true 表示用户处理了下载完成后续的事件 ，false 默认交给AgentWeb 处理
         */
        @Override
        public boolean onResult(Throwable throwable, Uri path, String url, Extra extra) {
            if (throwable == null) { //下载成功
                //file:///storage/emulated/0/Android/data/com.example.gq.effect/cache/agentweb-cache/2896ca08e0830de89bc93e2b9fc1ed2b/natural_12-hbsddz_1.5.5.apk
//                File file = new File(path.getPath());
//                if(file.exists()){
//                    file.delete();
//                }
                if(downLoadListener!=null){
                    downLoadListener.downFinish(path.getPath());
                }
            } else {//下载失败
                if(downLoadListener!=null){
                    downLoadListener.downFinish(null);
                }
            }
            return false; // true  不会发出下载完成的通知 , 或者打开文件
        }
    };
单独运行插件是可以下载完成的

**Comment by woleigeququ** [comment]
重新发下，刚刚格式有点乱
代码就是主程序RePlugin.startActivity(this, intent);
插件启动后去加载一个有下载的url
private IAgentWebSettings getAbsAgentSettings() {
return new AbsAgentWebSettings() {
private AgentWeb mAgentWeb;

        @Override
        protected void bindAgentWebSupport(AgentWeb agentWeb) {
            this.mAgentWeb = agentWeb;
        }

        @Override
        public WebListenerManager setDownloader(WebView webView, android.webkit.DownloadListener downloadListener) {
            return super.setDownloader(webView,
                    DefaultDownloadImpl.create(
                            (Activity) webView.getContext(),
                            webView,
                            mSimpleDownloadListener,
                            this.mAgentWeb.getPermissionInterceptor()));
        }
    };
}

private DownloadListener mSimpleDownloadListener = new DownloadListener() {
    /**
     *
     * @param url                下载链接
     * @param userAgent          UserAgent
     * @param contentDisposition ContentDisposition
     * @param mimetype           资源的媒体类型
     * @param contentLength      文件长度
     * @param extra              下载配置 ， 用户可以通过 Extra 修改下载icon ， 关闭进度条 ， 是否强制下载。
     * @return true 表示用户处理了该下载事件 ， false 交给 AgentWeb 下载
     */
    @Override
    public boolean onStart(String url, String userAgent, String contentDisposition, String mimetype, long contentLength, Extra extra) {
        if(!mOperator.isAccessWorkPage) {
            return true;
        }

        extra.setBreakPointDownload(true) // 是否开启断点续传
                .setConnectTimeOut(6000) // 连接最大时长
                .setBlockMaxTime(10 * 60 * 1000)  // 以8KB位单位，默认60s ，如果60s内无法从网络流中读满8KB数据，则抛出异常
                .setDownloadTimeOut(Long.MAX_VALUE) // 下载最大时长
                .setParallelDownload(true)  // 串行下载更节省资源
                .setEnableIndicator(true)  // false 关闭进度通知
.setAutoOpen(true) // 下载完成自动打开
.setForceDownload(true); // 强制下载，不管网络类型
if(downLoadListener!=null){
downLoadListener.downStart();
}
return false;
}

    /**
     * @param url  下载链接
     * @param loaded  已经下载的长度
     * @param length    文件的总大小
     * @param usedTime   耗时 ，单位ms
     * 注意该方法回调在子线程 ，线程名 AsyncTask #XX 或者 AgentWeb # XX
     */
    @Override
    public void onProgress(String url, long loaded, long length, long usedTime) {
super.onProgress(url, loaded, length, usedTime);
}

    /**
     * @param path 文件的绝对路径
     * @param url  下载地址
     * @param throwable    如果异常，返回给用户异常
     * @return true 表示用户处理了下载完成后续的事件 ，false 默认交给AgentWeb 处理
     */
    @Override
    public boolean onResult(Throwable throwable, Uri path, String url, Extra extra) {
        if (throwable == null) { //下载成功
if(downLoadListener!=null){
downLoadListener.downFinish(path.getPath());
}
} else {//下载失败
if(downLoadListener!=null){
downLoadListener.downFinish(null);
}
}
return false; // true 不会发出下载完成的通知 , 或者打开文件
}
};
单独运行插件是可以下载完成的

**Comment by Justson** [comment]
用最新版吧

**Comment by woleigeququ** [comment]
把之前的4个依赖换成下面这三个就行了吗， 需要改动代码吗
api 'com.just.agentweb:agentweb:4.1.2' // (必选)
 api 'com.just.agentweb:filechooser:4.1.2'// (可选)
 api 'com.download.library:Downloader:4.1.2'// (可选)

**Comment by Justson** [comment]
最新Sample有小幅改动

**Comment by woleigeququ** [comment]
过不了编译 ...
Program type already present: com.just.agentweb.Action$1
Message{kind=ERROR, text=Program type already present: com.just.agentweb.Action$1, sources=[Unknown source file], tool name=Optional.of(D8)}
我看不懂，不知道该怎么解决，修改以后下载的代码就按sample里那样子写的

**Comment by Justson** [comment]
clean

**Comment by woleigeququ** [comment]
用了新版本了，还是会停住..
