### ISSUE TITLE
Demo运行后下载完成后的安装包出现解析包时出现问题 

### ISSUE THREAD

**Issue by wuzhupc** [Justson/Downloader#9]
在3台手机上一台模拟器上，一台正常，2台出现解析包时出现问题。
正常的是xiaomi mix 2x android10 模拟器6.0的系统
出错的一台是Nexus 5X android 7.1.1 另一台出错的是华为的（别人的，比较旧的机子，只是让帮运行一下，同样的问题）

**Comment by Justson** [comment]
这不是库的问题
